// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsOUL8LlsH-6OrtKm1HFyGiLdM2tf1rLc',
    appId: '1:564536630602:web:52223dcf50fd32643b75b3',
    messagingSenderId: '564536630602',
    projectId: 'guard-time-app',
    authDomain: 'guard-time-app.firebaseapp.com',
    storageBucket: 'guard-time-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4U6EBOX1dTi9Bp9jSXsexgUkQiSeom8',
    appId: '1:564536630602:android:9422b9f0f366bfe63b75b3',
    messagingSenderId: '564536630602',
    projectId: 'guard-time-app',
    storageBucket: 'guard-time-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfF28OSaE_Zw0WD1ty35s2Dmk7Bb0x67U',
    appId: '1:564536630602:ios:d5c864a9ffdd334a3b75b3',
    messagingSenderId: '564536630602',
    projectId: 'guard-time-app',
    storageBucket: 'guard-time-app.firebasestorage.app',
    iosBundleId: 'com.example.parentsApp',
  );
}
